name: buildAndTest

on:
  pull_request:
    branches: main

jobs:
  Test-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Test utility functions
        run: npm run test

      - name: Build with yarn
        run: npm run build
